# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/development/cicd/templates/
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

image: golang:latest



stages:
  - test
  - build
# - deploy

format:
  stage: test
  before_script:
    - apt install gcc libgtk-3-dev libcairo2-dev libglib2.0-dev -y
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test ./test/...

compile:
  stage: build
  before_script:
    - apt install gcc libgtk-3-dev libcairo2-dev libglib2.0-dev -y
  script:
    - mkdir -p bin
    - go build -o bin ./...
  artifacts:
    paths:
      - bin

# deploy:
#  stage: deploy
#  script: echo "Define your deployment script!"
#  environment: production
